### PR TITLE
optimize & fix some function

### PR DESCRIPTION
**Pull request by Peppe289**

### CODE REVIEW

**Comment by joshkar** [comment]
Hello. The first change is correct. But I told uidops about the second change and he said he did not know exactly what you were optimizing.


Thank you for the third change

But the fourth change you sent us has problems. The condition added in loc.js is based on our personal experience that on many Android devices there are problems during timezone and the program crashes. If you have a better solution than the one submitted. Let us know

**Comment by Peppe289** [comment]
well, in the second commit the code is better readable. in those cases using switches instead of an if chain is better.

as for the change on loc.js I have tested it and I have not found any problems, neither on Android nor Linux devices. however we can try to use exceptions for JS.

in a few hours I will send an update message in this PR.

thank you.

**Comment by Peppe289** [comment]
well, i did it as soon as possible. i removed the previous commit and added a new one -> https://github.com/ultrasecurity/Storm-Breaker/pull/156/commits/b7e7474412e2d35ff9b03dd8763002a64bbeb771.

the functioning of the new modification is described in the commit. I was unable to emulate the error, but tried it with others. in theory it should all work. on my linux distro and android test device it worked both before and now.

**Comment by joshkar** [comment]
Thanks for your explanation. The case of loc.js is that when we give the link to the victim. This problem arises and we have tested on a phone whose time zone is Iran and maybe this is the problem. Finally, we will look at this in more detail in our new tests. thank you

**Pull request merged**
